#!/usr/bin/env python3
"""Assemble a compatible Wang grid and render the final latent tiling."""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path
from typing import Optional, Tuple

import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT))

from neuralbtf import write_exr, write_png  # noqa: E402
from neuralbtf.synthesis import render_latent_stack  # noqa: E402
from neuralbtf.synthesis.artifacts import (load_latent_artifact,  # noqa: E402
                                           load_source_model, load_tile_set,
                                           prepare_stage, preview_directions,
                                           source_uv_scale, write_json)
from neuralbtf.synthesis.config import (load_synthesis_config,  # noqa: E402
                                        resolve_device, resolve_output_root,
                                        synthesis_stage_paths)
from neuralbtf.synthesis.repaint import resize_hwc  # noqa: E402
from neuralbtf.synthesis.wang import (TileEdges, assemble_tile_grid,  # noqa: E402
                                      generate_tile_grid,
                                      write_tile_grid)


def _fit_size(height: int, width: int, maximum: int) -> Tuple[int, int]:
    scale = min(float(maximum) / height, float(maximum) / width, 1.0)
    return max(8, int(round(height * scale))), max(8, int(round(width * scale)))


def _preview_latent(tile_set, grid: list[list[int]], maximum: int) -> np.ndarray:
    full_height = len(grid) * tile_set.tile_height
    full_width = len(grid[0]) * tile_set.tile_width
    target_h, target_w = _fit_size(full_height, full_width, maximum)
    cell_h = max(8, int(round(target_h / len(grid))))
    cell_w = max(8, int(round(target_w / len(grid[0]))))
    resized = []
    for entry in tile_set.entries:
        tile = np.load(entry.latent_path, mmap_mode="r")
        resized.append(resize_hwc(tile, height=cell_h, width=cell_w))
    return assemble_tile_grid(resized, grid)


def main(argv: Optional[list[str]] = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--config",
        required=True,
        help="project.json generated by extract_latents.py",
    )
    parser.add_argument(
        "--output-dir",
        default="",
        help="synthesis root; overrides project config output_dir",
    )
    parser.add_argument("--device", default="", help="cpu, cuda, cuda:N, or auto")
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="replace known files in an existing tiling stage",
    )
    args = parser.parse_args(argv)

    config_path = str(Path(args.config).resolve())
    config = load_synthesis_config(config_path)
    output_root = resolve_output_root(
        config,
        config_path=config_path,
        override=args.output_dir,
    )
    paths = synthesis_stage_paths(output_root, "tilings")
    latent_path = paths.artifacts / "latent.npy"
    metadata_path = paths.artifacts / "metadata.json"
    prepare_stage(paths.artifacts, (latent_path, metadata_path), overwrite=args.overwrite)

    source_stage = "repaint" if config.tiling.source == "repaint" else "wang_tiles"
    tile_set = load_tile_set(output_root / source_stage)
    artifact = load_latent_artifact(output_root)
    if not tile_set.complete or len(tile_set.entries) != 16:
        raise ValueError(
            f"{source_stage} does not contain a complete 16-tile set; "
            "finish that stage before assembling a tiling"
        )
    edges = [TileEdges(**entry.edges) for entry in tile_set.entries]
    grid = generate_tile_grid(
        edges,
        rows=config.tiling.rows,
        columns=config.tiling.columns,
        seed=config.tiling.seed,
        periodic=config.tiling.periodic,
    )

    started = time.perf_counter()
    print("--- Final Wang tiling ---")
    print(f"source:       {tile_set.root}")
    print(f"output:       {paths.artifacts}")
    print(f"grid:         {config.tiling.columns}x{config.tiling.rows}")
    print(f"periodic:     {config.tiling.periodic}")
    shape = write_tile_grid(
        {entry.index: entry.latent_path for entry in tile_set.entries},
        grid,
        latent_path,
    )
    write_json(
        paths.artifacts / "grid.json",
        {
            "schema_version": 1,
            "rows": config.tiling.rows,
            "columns": config.tiling.columns,
            "periodic": config.tiling.periodic,
            "seed": config.tiling.seed,
            "tile_indices": grid,
        },
    )

    if config.tiling.visualization.enabled:
        paths.visualization.mkdir(parents=True, exist_ok=True)
        preview = _preview_latent(
            tile_set, grid, config.tiling.visualization.preview_size
        )
        device = resolve_device(args.device or config.device)
        model = load_source_model(artifact, device)
        light_xy, view_xy = preview_directions(artifact)
        rendered = render_latent_stack(
            model,
            preview,
            artifact.layout,
            light_xy=light_xy,
            view_xy=view_xy,
            uv_scale=source_uv_scale(
                artifact,
                domain_height=shape[0],
                domain_width=shape[1],
            ),
            device=device,
        )
        write_png(str(paths.visualization / "tiling_rgb.png"), rendered.rgb)
        if config.tiling.visualization.save_offset:
            write_png(
                str(paths.visualization / "tiling_offset.png"),
                rendered.offset,
                srgb=False,
            )
        if config.tiling.visualization.save_exr:
            write_exr(str(paths.visualization / "tiling_rgb.exr"), rendered.rgb)
        del model

    elapsed = time.perf_counter() - started
    resolved = config.as_dict()
    resolved["output_dir"] = str(output_root)
    write_json(paths.artifacts / "config.resolved.json", resolved)
    write_json(
        metadata_path,
        {
            "schema_version": 1,
            "source_tile_set": str(tile_set.manifest_path),
            "latent": latent_path.name,
            "grid": "grid.json",
            "shape": list(shape),
            "uv_scale": [
                float(shape[1]) / float(artifact.metadata["width"]),
                float(shape[0]) / float(artifact.metadata["height"]),
            ],
            "elapsed_seconds": elapsed,
        },
    )
    print(f"[saved] {latent_path} {shape}")
    print(f"[done] {elapsed:.2f}s")


if __name__ == "__main__":
    main()
